# Introduction to Torch

## Overview

Torch is a pretty nice library, from what I've seen so far. 
This tutorial follows the 
[introductory](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) tutorial. I'll leave references where I diverge. 

Importing torch is . . . nice, and you don't have to alias it, 
because the name isn't a paragraph long. 

In [1]:
import torch

## CUDA

Interacting with CUDA enabled devices has also been easy,
straigthforward, and feature packed.

[Torch CUDA Docs](https://pytorch.org/docs/stable/cuda.html?highlight=cuda#module-torch.cuda)

There are also additional functions to easily handle memory management,
cross device communication, and data movement. 

In [2]:
print(f'[+] Current BLAS Handle: {torch.cuda.current_blas_handle()}')
print(f'[+] Current Device: {torch.cuda.current_device()}')
print(f'[+] Current Stream: {torch.cuda.current_stream()}')
print(f'[+] Current Device Count: {torch.cuda.device_count()}')

[+] Current BLAS Handle: 94143602460880
[+] Current Device: 0
[+] Current Stream: <torch.cuda.Stream device=cuda:0 cuda_stream=0x0>
[+] Current Device Count: 1


Moving tensors around devices is easy with the `.to` method.

In [3]:
x = torch.zeros(5, 5)
y = torch.ones_like(x)

device = torch.device('cuda')

x.to(device)

x + y

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [4]:
print(f'[+] x: {x}')
print(f'[+] y: {y}')

[+] x: tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
[+] y: tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


## Tensors

In [5]:
x = torch.rand(5, 5)
print(f'[+] Random Tensor:\n{x}')

[+] Random Tensor:
tensor([[0.7088, 0.0513, 0.1381, 0.7639, 0.7697],
        [0.3305, 0.2283, 0.8394, 0.9281, 0.6790],
        [0.4273, 0.5145, 0.2997, 0.6779, 0.8971],
        [0.3548, 0.5899, 0.2742, 0.5508, 0.6908],
        [0.1419, 0.3622, 0.7334, 0.6258, 0.2114]])


In [6]:
x = torch.zeros(5, 5, dtype=torch.long)
print(f'[+] Tensor With Specified Data Type (long):\n{x}')

[+] Tensor With Specified Data Type (long):
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [7]:
# Tensors can be constructed from data directly.
import numpy as np

x = np.ones((5, 5))
y = torch.tensor(x)
z = torch.tensor([5.0, 4.5, 6.7])

print(f'[+] From Numpy Array:\n{y}')
print(f'[+] From Python List:\n{z}')

[+] From Numpy Array:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
[+] From Python List:
tensor([5.0000, 4.5000, 6.7000])


We can create tensors based on other tensors.
These will mirror the properties of the original 
tensor, unless explicitly specified. This includes
data type.

When calling `torch.Tensor.new_*()`. The datatype of
the allocated values will match that of the original
tensor. Though the size has to be specified. 

In [8]:
x = torch.ones((5, 5), dtype=torch.float)
x = x.new_ones(5, 3)
print(f'[+] x:\n{x}')

[+] x:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


The `*_like()` methods behave the same. They
will share the datatype unless otherwise specififed.

In [9]:
x = torch.ones((5, 5), dtype=torch.float)
y = torch.randn_like(x)
z = torch.randn_like(x, dtype=torch.double)

print(f'[+] Random With Same Data Type:\n{y}')
print(f'[+] Random With Specified Data Type:\n{z}')

[+] Random With Same Data Type:
tensor([[ 0.0204, -0.7842,  0.1891, -1.6255, -0.5185],
        [-0.3987,  0.6290,  1.6027,  0.0829,  1.0554],
        [ 1.2418, -2.3342,  1.3321,  0.8430,  0.0399],
        [-0.3995, -0.6974,  1.9661, -0.2528,  0.1039],
        [-1.2914, -1.4067,  0.6872, -1.4799, -0.2913]])
[+] Random With Specified Data Type:
tensor([[-0.3544,  0.4366, -1.1455, -0.9615, -1.6178],
        [-0.5426, -1.4451, -1.4246, -0.4415,  1.7996],
        [-0.0194, -1.6750, -1.0420, -0.6141,  0.5710],
        [ 1.1370, -0.1802,  1.2201, -0.9857, -0.0550],
        [-0.1125, -1.5007, -1.4354,  0.1511,  0.6555]], dtype=torch.float64)


Getting the `.size()` of a tensor returns a tensor
with the dimensions. 

In [10]:
print(f'[+] x.size(): {x.size()}')

[+] x.size(): torch.Size([5, 5])


## Operations

Operations can be done via operator overloading
in some cases. Note that `*` performs elementwise
multiplication, as does `Tensor.mul(a, b)`. For 
matrix multiplication, use `Tensor.matmul(a, b)`.

For full details on torch operations, see
[Operations](https://pytorch.org/docs/stable/torch.html).

In [11]:
x = torch.rand((5, 3))
y = torch.ones_like(x)

print(x + y == torch.add(x, y))

print(x * y == torch.mul(x, y))

x = torch.rand((5, 3))
y = torch.ones((3, 3), dtype=torch.float)
x.matmul(y)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


tensor([[0.7031, 0.7031, 0.7031],
        [1.8957, 1.8957, 1.8957],
        [1.9989, 1.9989, 1.9989],
        [2.3096, 2.3096, 2.3096],
        [1.6977, 1.6977, 1.6977]])

Operations can also be performed in place. Any
method with `_` at the end modifies data in place.
For example `x.t_()` will transpose `x` in place.

In [12]:
x = torch.ones((5, 3))
print(f'[+] x:\n{x}')
x.t_()
print(f'[+] x.t:\n{x}')

[+] x:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
[+] x.t:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Torch Tensors support numpy style indexing. 

In [13]:
x = torch.randn((5, 6))
print(f'[+] x:\n{x}\n')
print(f'[+] Fourth Column x[:, 3]:\n{x[:, 3]}\n')
print(f'[+] Second Row x[1, :]:\n{x[1, :]}\n')

[+] x:
tensor([[-1.2415,  0.7700, -0.2028,  0.3694,  0.2475, -0.4516],
        [ 0.6865, -0.4636, -0.5509,  0.9202,  0.2195, -0.2910],
        [ 0.5653, -0.4738,  1.4267, -0.9469, -1.8921,  0.3963],
        [ 0.2283, -0.0609,  1.3677, -1.6544,  1.0972, -0.2172],
        [ 0.7387, -1.0990, -0.2476,  0.3265,  0.1526, -0.3760]])

[+] Fourth Column x[:, 3]:
tensor([ 0.3694,  0.9202, -0.9469, -1.6544,  0.3265])

[+] Second Row x[1, :]:
tensor([ 0.6865, -0.4636, -0.5509,  0.9202,  0.2195, -0.2910])



In [14]:
x = torch.zeros((5, 5))
x.add_(1)
print(f'[+] x:\n{x}')

[+] x:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


The way reshaping is done in torch is ideal. The method
`.view()` returns a view of the memory location of the
original tensor with the specified shape. So, if you 
modify the original tensor, the view created will refer
to the data in that original tensor. Now, if the original
tensor is overwritten, such as when using `x = torch.zeros()`,
the views will still point to the original memory location, 
and won't be modified. 

In [15]:
x = torch.zeros((4, 4))
y = x.view((16))
z = x.view((8, 2))

print(f'[+] x:\n{x}\n')
print(f'[+] y:\n{y}\n')
print(f'[+] z:\n{z}\n')

[+] x:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

[+] y:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

[+] z:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])



In [16]:
x.add_(1)

print(f'[+] x:\n{x}\n')
print(f'[+] y:\n{y}\n')
print(f'[+] z:\n{z}\n')

[+] x:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

[+] y:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

[+] z:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])



In [17]:
x = torch.zeros((5, 5))
print(f'[+] x:\n{x}\n')
print(f'[+] y:\n{y}\n')

[+] x:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

[+] y:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])



We can also use numpy bridges to read the
memory location of a tensor in numpy. 

In [18]:
x = torch.ones(5, 5)
n = x.numpy()

print(f'[+] n:\n{n}\n')
x.add_(1)
print(f'[+] n:\n{n}\n')

[+] n:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[+] n:
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]



Likewise, we can construct tensor views over numpy arrays.

In [19]:
a = np.ones(5)
b = torch.from_numpy(a)

print(f'[+] b:\n{b}\n')
np.add(a, 1, out=a)
print(f'[+] b:\n{b}\n')

[+] b:
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

[+] b:
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

